/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guihangamn;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {//หน้าเมนูก็จะต้องไป link กับ login , admin , hall of fame 
    //ต้องสร้าง attribute สำหรับ link 3 ตัว และมี Method สำหรับ ลิ้ง 3 ตัวเช่นกัน
    private Login controlLogin;
    private Admin controlAdmin;
    private Score controlScore;
    
   
    /**
     * Creates new form MyClass
     */
    //สาม method นี้จะทำให้พอเราไปหน้า login, admin, score แล้วเรายังสามารถคุมการเปิดปิดของเมนูเรไาด้นั่นเอง
    //จะต้องมีควบคู่เช่นนี้เสมอ
    public void linkToLogin(Login controlLogin){
        this.controlLogin=controlLogin;
    }
    
    public void linkToAdmin(Admin controlAdmin){
        this.controlAdmin=controlAdmin;
    }
    
    public void linkToScore(Score controlScore){
        this.controlScore=controlScore;
    }
    
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    
        InputStream is = Login.class.getResourceAsStream("OUTLAW.ttf");
        
        try {

            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (FontFormatException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        admin = new javax.swing.JButton();
        login = new javax.swing.JButton();
        score = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);
        setIconImages(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setFont(new java.awt.Font("Outlaw ", 0, 80)); // NOI18N
        logo.setForeground(new java.awt.Color(76, 57, 42));
        logo.setText("Hangman Is Real");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 620, 120));

        admin.setFont(new java.awt.Font("Outlaw ", 0, 48)); // NOI18N
        admin.setForeground(new java.awt.Color(76, 57, 42));
        admin.setText("ShERiff area");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        getContentPane().add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 280, 50));

        login.setFont(new java.awt.Font("Outlaw ", 0, 48)); // NOI18N
        login.setForeground(new java.awt.Color(76, 57, 42));
        login.setText("Desperado");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 280, 50));

        score.setFont(new java.awt.Font("Outlaw ", 0, 48)); // NOI18N
        score.setForeground(new java.awt.Color(76, 57, 42));
        score.setText("Hall Of Fame");
        score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreActionPerformed(evt);
            }
        });
        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 280, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guihangamn/hangman.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Kuku");
        
    }//GEN-LAST:event_adminActionPerformed
    //เมื่อคลิกปุ่ม login ทำงานแล้ว method นี้จะถูกสั่งงานคือให้ไปเปิดหน้า UI login
    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        Login login =new Login();
        login.linkToMenu(this);//ทำการผูกเมนูเข้าด้วยกันคือชี้ไปที่ Addre เดียวกัน
        login.setVisible(true);//อย่าลืม setVisible ให้มองเห้นเสมอไม่งั้นจะไม่ขึ้น
        
        
    }//GEN-LAST:event_loginActionPerformed

    private void scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreActionPerformed

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin;
    private javax.swing.JLabel background;
    private javax.swing.JButton login;
    private javax.swing.JLabel logo;
    private javax.swing.JButton score;
    // End of variables declaration//GEN-END:variables
}
