/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guihangamn;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author csc
 */
public class Play extends javax.swing.JFrame {

    private Menu menu;
    private HangmanStructure hangman=new HangmanStructure(this);
    
    /**
     * Creates new form Play
     * @param e
     */
    
    

    public Play() {
        initComponents();
        setLocationRelativeTo(null);
        //menu.hide();
        //hangman.linkToPlay(this);//ทำให้ Hangman เราควบคุม play ได้แล้ว หน้าจะผูกกัน
        InputStream is = Login.class.getResourceAsStream("OUTLAW.ttf");
        
        try {
            Font font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (FontFormatException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public void allVisibleButton() {//จะทำหน้าที่
    aButton.setVisible(true);
    bButton.setVisible(true);
    cButton.setVisible(true);
    dButton.setVisible(true);
    eButton.setVisible(true);
    fButton.setVisible(true);
    gButton.setVisible(true);
    hButton.setVisible(true);
    iButton.setVisible(true);
    jButton.setVisible(true);
    kButton.setVisible(true);
    lButton.setVisible(true);
    mButton.setVisible(true);
    nButton.setVisible(true);
    oButton.setVisible(true);
    pButton.setVisible(true);
    qButton.setVisible(true);
    uButton.setVisible(true);
    rButton.setVisible(true);
    sButton.setVisible(true);
    tButton.setVisible(true);
    uButton.setVisible(true);
    vButton.setVisible(true);
    wButton.setVisible(true);
    xButton.setVisible(true);
    yButton.setVisible(true);
    zButton.setVisible(true); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qButton = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        yButton = new javax.swing.JButton();
        uButton = new javax.swing.JButton();
        iButton = new javax.swing.JButton();
        aButton = new javax.swing.JButton();
        sButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        fButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        kButton = new javax.swing.JButton();
        lButton = new javax.swing.JButton();
        zButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        vButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        mButton = new javax.swing.JButton();
        oButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        hButton = new javax.swing.JButton();
        wordLogo = new javax.swing.JLabel();
        yourWordForInput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qButton.setText("Q");
        qButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qButtonActionPerformed(evt);
            }
        });
        getContentPane().add(qButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 415, 47, 38));

        wButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wButton.setText("W");
        wButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wButtonActionPerformed(evt);
            }
        });
        getContentPane().add(wButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 415, 57, 38));

        eButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eButton.setText("E");
        eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });
        getContentPane().add(eButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 415, 47, 38));

        rButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rButton.setText("R");
        rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonActionPerformed(evt);
            }
        });
        getContentPane().add(rButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 415, 47, 38));

        tButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tButton.setText("T");
        tButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 415, 47, 38));

        yButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yButton.setText("Y");
        yButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yButtonActionPerformed(evt);
            }
        });
        getContentPane().add(yButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 415, 47, 38));

        uButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uButton.setText("U");
        uButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uButtonActionPerformed(evt);
            }
        });
        getContentPane().add(uButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 415, 47, 38));

        iButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        iButton.setText("I");
        iButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iButtonActionPerformed(evt);
            }
        });
        getContentPane().add(iButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 415, 47, 38));

        aButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        aButton.setText("A");
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });
        getContentPane().add(aButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 459, 47, 38));

        sButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sButton.setText("S");
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 459, 47, 38));

        dButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dButton.setText("D");
        dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 459, 47, 38));

        fButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fButton.setText("F");
        fButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonActionPerformed(evt);
            }
        });
        getContentPane().add(fButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 459, 47, 38));

        gButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gButton.setText("G");
        gButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gButtonActionPerformed(evt);
            }
        });
        getContentPane().add(gButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 459, 47, 38));

        jButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton.setText("J");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 459, 47, 38));

        kButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        kButton.setText("K");
        kButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonActionPerformed(evt);
            }
        });
        getContentPane().add(kButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 459, 47, 38));

        lButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lButton.setText("L");
        lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 459, 47, 38));

        zButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zButton.setText("Z");
        zButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zButtonActionPerformed(evt);
            }
        });
        getContentPane().add(zButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 503, 47, 38));

        xButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        xButton.setText("X");
        xButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xButtonActionPerformed(evt);
            }
        });
        getContentPane().add(xButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 503, 47, 38));

        cButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cButton.setText("C");
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 503, 47, 38));

        vButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vButton.setText("V");
        vButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonActionPerformed(evt);
            }
        });
        getContentPane().add(vButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 503, 47, 38));

        bButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bButton.setText("B");
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });
        getContentPane().add(bButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 503, 47, 38));

        nButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nButton.setText("N");
        nButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 503, 47, 38));

        mButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mButton.setText("M");
        mButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 503, 47, 38));

        oButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        oButton.setText("O");
        oButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oButtonActionPerformed(evt);
            }
        });
        getContentPane().add(oButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 415, 47, 38));

        pButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pButton.setText("P");
        pButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonActionPerformed(evt);
            }
        });
        getContentPane().add(pButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 415, 47, 38));

        hButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hButton.setText("H");
        hButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 459, 47, 38));

        wordLogo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        wordLogo.setText("WORD");
        getContentPane().add(wordLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 80, 50));

        yourWordForInput.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(yourWordForInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 300, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        // TODO add your handling code here:
        sButton.setVisible(false);
        hangman.enterWord("s");
        
    }//GEN-LAST:event_sButtonActionPerformed

    private void qButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qButtonActionPerformed
        // TODO add your handling code here:
        qButton.setVisible(false);
        hangman.enterWord("q");
    }//GEN-LAST:event_qButtonActionPerformed

    private void wButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wButtonActionPerformed
        // TODO add your handling code here:
        wButton.setVisible(false);
        hangman.enterWord("w");
    }//GEN-LAST:event_wButtonActionPerformed

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
        // TODO add your handling code here:
        eButton.setVisible(false);
        hangman.enterWord("e");
    }//GEN-LAST:event_eButtonActionPerformed

    private void rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonActionPerformed
        // TODO add your handling code here:
        rButton.setVisible(false);
        hangman.enterWord("r");
    }//GEN-LAST:event_rButtonActionPerformed

    private void tButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonActionPerformed
        // TODO add your handling code here:
        tButton.setVisible(false);
        hangman.enterWord("t");
    }//GEN-LAST:event_tButtonActionPerformed

    private void yButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yButtonActionPerformed
        // TODO add your handling code here:
        yButton.setVisible(false);
        hangman.enterWord("y");
    }//GEN-LAST:event_yButtonActionPerformed

    private void uButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uButtonActionPerformed
        // TODO add your handling code here:
        uButton.setVisible(false);
        hangman.enterWord("u");
    }//GEN-LAST:event_uButtonActionPerformed

    private void iButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iButtonActionPerformed
        // TODO add your handling code here:
        iButton.setVisible(false);
        hangman.enterWord("i");
    }//GEN-LAST:event_iButtonActionPerformed

    private void oButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oButtonActionPerformed
        // TODO add your handling code here:
        oButton.setVisible(false);
        hangman.enterWord("o");
    }//GEN-LAST:event_oButtonActionPerformed

    private void pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonActionPerformed
        // TODO add your handling code here:
        pButton.setVisible(false);
        hangman.enterWord("p");
    }//GEN-LAST:event_pButtonActionPerformed

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        // TODO add your handling code here:
        aButton.setVisible(false);
        hangman.enterWord("a");
    }//GEN-LAST:event_aButtonActionPerformed

    private void dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dButtonActionPerformed
        // TODO add your handling code here:
        dButton.setVisible(false);
        hangman.enterWord("d");
    }//GEN-LAST:event_dButtonActionPerformed

    private void fButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonActionPerformed
        // TODO add your handling code here:
        fButton.setVisible(false);
        hangman.enterWord("f");
    }//GEN-LAST:event_fButtonActionPerformed

    private void gButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gButtonActionPerformed
        // TODO add your handling code here:
        gButton.setVisible(false);
        hangman.enterWord("g");
    }//GEN-LAST:event_gButtonActionPerformed

    private void hButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hButtonActionPerformed
        // TODO add your handling code here:
        hButton.setVisible(false);
        hangman.enterWord("h");
    }//GEN-LAST:event_hButtonActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        // TODO add your handling code here:
        jButton.setVisible(false);
        hangman.enterWord("j");
    }//GEN-LAST:event_jButtonActionPerformed

    private void kButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonActionPerformed
        // TODO add your handling code here:
        kButton.setVisible(false);
        hangman.enterWord("k");
    }//GEN-LAST:event_kButtonActionPerformed

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lButtonActionPerformed
        // TODO add your handling code here:
        lButton.setVisible(false);
        hangman.enterWord("l");
    }//GEN-LAST:event_lButtonActionPerformed

    private void zButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zButtonActionPerformed
        // TODO add your handling code here:
        zButton.setVisible(false);
        hangman.enterWord("z");
    }//GEN-LAST:event_zButtonActionPerformed

    private void xButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xButtonActionPerformed
        // TODO add your handling code here:
        xButton.setVisible(false);
        hangman.enterWord("x");
    }//GEN-LAST:event_xButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        // TODO add your handling code here:
        cButton.setVisible(false);
        hangman.enterWord("c");
    }//GEN-LAST:event_cButtonActionPerformed

    private void vButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonActionPerformed
        // TODO add your handling code here:
        vButton.setVisible(false);
        hangman.enterWord("v");
    }//GEN-LAST:event_vButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        // TODO add your handling code here:
        bButton.setVisible(false);
        hangman.enterWord("b");
    }//GEN-LAST:event_bButtonActionPerformed

    private void nButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nButtonActionPerformed
        // TODO add your handling code here:
        nButton.setVisible(false);
        hangman.enterWord("n");
    }//GEN-LAST:event_nButtonActionPerformed

    private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonActionPerformed
        // TODO add your handling code here:
        mButton.setVisible(false);
        hangman.enterWord("m");
    }//GEN-LAST:event_mButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Play().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton aButton;
    javax.swing.JButton bButton;
    javax.swing.JButton cButton;
    javax.swing.JButton dButton;
    javax.swing.JButton eButton;
    javax.swing.JButton fButton;
    javax.swing.JButton gButton;
    javax.swing.JButton hButton;
    javax.swing.JButton iButton;
    javax.swing.JButton jButton;
    javax.swing.JButton kButton;
    javax.swing.JButton lButton;
    javax.swing.JButton mButton;
    javax.swing.JButton nButton;
    javax.swing.JButton oButton;
    javax.swing.JButton pButton;
    javax.swing.JButton qButton;
    javax.swing.JButton rButton;
    javax.swing.JButton sButton;
    javax.swing.JButton tButton;
    javax.swing.JButton uButton;
    javax.swing.JButton vButton;
    javax.swing.JButton wButton;
    javax.swing.JLabel wordLogo;
    javax.swing.JButton xButton;
    javax.swing.JButton yButton;
    public javax.swing.JLabel yourWordForInput;
    javax.swing.JButton zButton;
    // End of variables declaration//GEN-END:variables

   
}
